#!/usr/bin/env python3
"""Generate the main-SAADI-compatible Jina late-chunking expansion table."""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Optional, Tuple


RANKING_VIEWS = ("gold", "silver_loose", "union_loose")
RANKING_VIEW_LABELS = {
    "gold": "Gold",
    "silver_loose": "Silver-L",
    "union_loose": "Union-L",
}
RANKING_METRICS = (
    ("ndcg@5", "NDCG@5"),
    ("recall@5", "Recall@5"),
    ("ndcg@10", "NDCG@10"),
    ("recall@10", "Recall@10"),
)
BINARY_VIEWS = ("gold_hit", "silver_strict_hit", "strict_union_hit")
BINARY_VIEW_LABELS = {
    "gold_hit": "Gold",
    "silver_strict_hit": "Silver-S",
    "strict_union_hit": "Union-S",
}
BINARY_METRICS = (("hit_rate@5", "HR@5"), ("hit_rate@10", "HR@10"))
DATASETS = (
    ("qasper_64k", "QASPER (64K)", 1372),
    ("musique_32k", "MuSiQue (32K)", 900),
)
RETRIEVER = "jina"
RETRIEVER_LABEL = "Jina"
CHUNK_SIZE = 500
OVERLAPS = (0, 25, 50)


@dataclass
class ResultCell:
    source: Path
    ranking: Dict[str, Dict[str, Optional[float]]]
    binary: Dict[str, Dict[str, Optional[float]]]


def parse_args() -> argparse.Namespace:
    project_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input-root",
        type=Path,
        default=project_root / "late_chunk_evaluations",
    )
    parser.add_argument(
        "--output-file",
        type=Path,
        default=project_root / "tables" / "table_jina_expanded_main_retrieval.tex",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Fail if any of the six expected evaluation rows is absent or incomplete.",
    )
    return parser.parse_args()


def _load_json(path: Path) -> Dict[str, object]:
    with path.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    if not isinstance(payload, dict):
        raise ValueError(f"Expected a JSON object in {path}")
    return payload


def _coerce_metric(value: object) -> Optional[float]:
    if value is None:
        return None
    return float(value)


def _load_cell(
    input_root: Path,
    dataset: str,
    expected_queries: int,
    overlap: int,
) -> Optional[ResultCell]:
    path = (
        input_root
        / dataset
        / RETRIEVER
        / f"c{CHUNK_SIZE}_o{overlap}"
        / "metrics_summary.json"
    )
    if not path.is_file():
        return None
    payload = _load_json(path)
    expected_values = {
        "dataset_name": dataset,
        "run_name": f"{RETRIEVER}/c{CHUNK_SIZE}_o{overlap}",
        "n_queries": expected_queries,
    }
    for field, expected in expected_values.items():
        if payload.get(field) != expected:
            raise ValueError(
                f"{path} {field} mismatch: expected {expected!r}, got {payload.get(field)!r}"
            )
    if not {5, 10}.issubset({int(value) for value in payload.get("k_values", [])}):
        raise ValueError(f"{path} must contain metrics at k=5 and k=10")

    raw_ranking = payload.get("ranking_metrics_by_view")
    raw_binary = payload.get("hit_rate_metrics_by_view")
    if not isinstance(raw_ranking, dict) or not isinstance(raw_binary, dict):
        raise ValueError(f"{path} is missing the main SAADI metric blocks")
    ranking = {
        view: {
            metric: _coerce_metric((raw_ranking.get(view) or {}).get(metric))
            for metric, _label in RANKING_METRICS
        }
        for view in RANKING_VIEWS
    }
    binary = {
        view: {
            metric: _coerce_metric((raw_binary.get(view) or {}).get(metric))
            for metric, _label in BINARY_METRICS
        }
        for view in BINARY_VIEWS
    }
    return ResultCell(source=path, ranking=ranking, binary=binary)


def _format_metric(value: Optional[float]) -> str:
    return "--" if value is None else f"{100.0 * value:.1f}"


def _escape(text: str) -> str:
    return text.replace("&", r"\&").replace("_", r"\_")


def _expected_keys() -> Tuple[Tuple[str, str, int, int], ...]:
    return tuple(
        (dataset, label, expected_queries, overlap)
        for dataset, label, expected_queries in DATASETS
        for overlap in OVERLAPS
    )


def build_table(cells: Dict[Tuple[str, int], ResultCell]) -> str:
    lines = [
        "% Auto-generated by tables/generate_jina_expanded_main_table.py",
        "% Uses the same 18 retrieval metrics and target definitions as the main SAADI table.",
        "% QASPER uses the exact SAADI 64K bundle (23 groups / 1372 queries).",
        "% MuSiQue uses the exact SAADI 32K 300-per-hop bundle (45 groups / 900 queries).",
        r"\begin{table*}[t]",
        r"\centering",
        (
            r"\caption{Jina late-chunking retrieval on the main SAADI context expansions. "
            r"Chunk size is 500 tokens; values are percentages.}"
        ),
        r"\label{tab:jina-late-chunking-expanded-main-retrieval}",
        r"\resizebox{\textwidth}{!}{%",
        r"\begin{tabular}{lllrrrrrrrrrrrrrrrrrr}",
        r"\toprule",
        (
            r"Dataset & Retriever & Method & \multicolumn{12}{c}{Ranking Metrics} "
            r"& \multicolumn{6}{c}{Binary Metrics} \\"
        ),
        r"\cmidrule(lr){4-15}\cmidrule(lr){16-21}",
        (
            r"& & & \multicolumn{4}{c}{Gold} & \multicolumn{4}{c}{Silver-L} "
            r"& \multicolumn{4}{c}{Union-L} & \multicolumn{2}{c}{Gold} "
            r"& \multicolumn{2}{c}{Silver-S} & \multicolumn{2}{c}{Union-S} \\"
        ),
        (
            r"& & & NDCG@5 & Recall@5 & NDCG@10 & Recall@10 "
            r"& NDCG@5 & Recall@5 & NDCG@10 & Recall@10 "
            r"& NDCG@5 & Recall@5 & NDCG@10 & Recall@10 "
            r"& HR@5 & HR@10 & HR@5 & HR@10 & HR@5 & HR@10 \\"
        ),
        r"\midrule",
    ]

    first_dataset = True
    for dataset, label, _expected_queries in DATASETS:
        if not first_dataset:
            lines.append(r"\midrule")
        first_dataset = False
        for overlap_index, overlap in enumerate(OVERLAPS):
            cell = cells.get((dataset, overlap))
            row = [
                _escape(label) if overlap_index == 0 else "",
                RETRIEVER_LABEL if overlap_index == 0 else "",
                f"Late Chunking (500/{overlap})",
            ]
            for view in RANKING_VIEWS:
                for metric, _metric_label in RANKING_METRICS:
                    row.append(
                        _format_metric(cell.ranking[view][metric]) if cell else "--"
                    )
            for view in BINARY_VIEWS:
                for metric, _metric_label in BINARY_METRICS:
                    row.append(
                        _format_metric(cell.binary[view][metric]) if cell else "--"
                    )
            lines.append(" & ".join(row) + " \\\\")

    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}%",
            r"}",
            r"\end{table*}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    cells: Dict[Tuple[str, int], ResultCell] = {}
    missing = []
    for dataset, _label, expected_queries, overlap in _expected_keys():
        cell = _load_cell(args.input_root, dataset, expected_queries, overlap)
        if cell is None:
            missing.append(f"{dataset}/{RETRIEVER}/c{CHUNK_SIZE}_o{overlap}")
        else:
            cells[(dataset, overlap)] = cell

    args.output_file.parent.mkdir(parents=True, exist_ok=True)
    args.output_file.write_text(build_table(cells), encoding="utf-8")
    print(f"Wrote {args.output_file.resolve()}")
    print(f"Loaded {len(cells)}/6 expected rows; missing={len(missing)}")
    if args.strict and missing:
        raise SystemExit(
            "Missing expected Jina expanded late-chunking rows:\n  "
            + "\n  ".join(missing)
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
